services:
  db:
    image: mysql:5.7.29
    container_name: nuxt_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tprices
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  frontend:
    image: node:18
    container_name: nuxt_frontend
    working_dir: /app/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm run dev"
    depends_on:
      backend:
        condition: service_started

  backend:
    image: node:18
    container_name: nuxt_backend
    working_dir: /app/backend
    ports:
      - "3030:3030"
    volumes:
      - ./backend:/app/backend
    environment:
      NODE_ENV: development
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: tprices
    command: sh -c "npm install && npm start"
    depends_on:
      db:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nuxt_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: